name: Checks

on:
  schedule:
    - cron: "0 */3 * * *"  # Every 3 hours
  workflow_dispatch:

jobs:
  site-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site: [AU, IT, CA]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and Chromium only
        run: |
          npm install
          npx playwright install chromium

      - name: Run site-specific Playwright tests
        run: |
          SITE=${{ matrix.site }}
          FILE_NAME=$(echo "$SITE" | tr '[:upper:]' '[:lower:]')
          mkdir -p reports/$SITE

          echo "Running ${FILE_NAME}.spec.ts only..."

          if npx playwright test sites/${FILE_NAME}.spec.ts; then
            echo "${SITE} ✅ Site check passed" > reports/$SITE/combined-status.txt
          else
            echo "${SITE} ❌ Site check failed" > reports/$SITE/combined-status.txt
          fi

      - name: Upload screenshots and performance CSV
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.site }}
          path: |
            screenshots/
            reports/performance-metrics-${{ matrix.site }}.csv

      - name: Upload site status file
        uses: actions/upload-artifact@v4
        with:
          name: status-${{ matrix.site }}
          path: reports/${{ matrix.site }}/combined-status.txt
