name: Playwright Site Status

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  site-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site: [AU] # You can extend this if needed later, e.g., [AU, CA, IT, US]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and Chromium only
        run: |
          npm install
          npx playwright install chromium

      - name: Run all Playwright tests in sites/ folder
        run: |
          SITE=${{ matrix.site }}
          mkdir -p reports/$SITE

          echo "Running all .spec.ts files in sites/ folder..."

          if npx playwright test sites/; then
            echo "${SITE} ✅ Site check passed" > reports/$SITE/combined-status.txt
          else
            echo "${SITE} ❌ Site check failed" > reports/$SITE/combined-status.txt
          fi

      - name: Upload screenshots and performance CSV
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.site }}
          path: |
            screenshots/
            reports/performance-metrics.csv

      - name: Upload site status file
        uses: actions/upload-artifact@v4
        with:
          name: status-${{ matrix.site }}
          path: reports/${{ matrix.site }}/combined-status.txt
