name: Website check automation

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  site-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site: [AU, CA, IT]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and Chromium only
        run: |
          npm install
          npx playwright install chromium
      - name: Run Playwright tests for ${{ matrix.site }}
        run: |
          SITE=${{ matrix.site }}
          mkdir -p reports/$SITE
          
          TEST_FILE="sites/${SITE}.spec.ts"
          echo "Running test file: $TEST_FILE"
          if npx playwright test "$TEST_FILE"; then
            echo "${SITE} ✅ Site check passed" > reports/$SITE/combined-status.txt
          else
            echo "${SITE} ❌ Site check failed" > reports/$SITE/combined-status.txt
          fi
      - name: Upload screenshots and performance CSV
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.site }}
          path: |
            screenshots/
            reports/performance-metrics.csv
      - name: Upload site status file
        uses: actions/upload-artifact@v4
        with:
          name: status-${{ matrix.site }}
          path: reports/${{ matrix.site }}/combined-status.txt
