name: Playwright html

on:
  workflow_dispatch:

jobs:
  site-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site: [AU, IT, CA, USAT]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and Chromium only
        run: |
          npm install
          npx playwright install chromium

      - name: Run site-specific Playwright tests
        run: |
          SITE=${{ matrix.site }}
          mkdir -p reports/$SITE
          npx playwright test sites/${SITE}.spec.ts

      - name: Generate HTML performance report
        run: SITE=${{ matrix.site }} node generateHtmlReport.js

      - name: Upload artifacts (screenshots, CSV, HTML)
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.site }}
          path: |
            screenshots/
            reports/performance-metrics-${{ matrix.site }}.csv
            reports/performance-report-${{ matrix.site }}.html
